export const SEND_EMAIL = "SEND_EMAIL";
export const ATTACH_FILE = "ATTACH_FILE";
export const DETACH_FILE = "DETACH_FILE";
export const GET_ALL_EMAIL_SENT = "GET_ALL_EMAIL_SENT";
export const GET_ALL_EMAIL_RECEIVED = "GET_ALL_EMAIL_RECEIVED";
export const SEARCH_EMAIL = "SEARCH_EMAIL";
